apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jsonplaceholder
  labels:
    app: jsonplaceholder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jsonplaceholder
    spec:
      containers:
      - name: jsonplaceholder
        image: jsonplaceholder
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
